<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Db77DataSeeder extends Seeder
{
    public function run(): void
    {
        // ── items — tambah produk pabrik agar SPK bisa match item_id ─────────
        // IDs 101-103 tidak bentrok dengan items seeder (IDs 1-4)
        DB::table('items')->insertOrIgnore([
            [
                'id'         => 101,
                'item_code'  => 'CUP-PP200',
                'item_name'  => 'Cup PP 200ml Bening',
                'uom'        => 'PCS',
                'created_at' => '2026-05-12 15:07:17',
                'updated_at' => '2026-05-12 15:07:17',
            ],
            [
                'id'         => 102,
                'item_code'  => 'TUT-PP38',
                'item_name'  => 'Tutup Botol PP 38mm',
                'uom'        => 'PCS',
                'created_at' => '2026-05-12 15:07:17',
                'updated_at' => '2026-05-12 15:07:17',
            ],
            [
                'id'         => 103,
                'item_code'  => 'GAL-PC19',
                'item_name'  => 'Galon PC 19L Biru Bening',
                'uom'        => 'PCS',
                'created_at' => '2026-05-12 15:07:17',
                'updated_at' => '2026-05-12 15:07:17',
            ],
        ]);

        // ── mfg_customers ─────────────────────────────────────────────────────
        DB::table('mfg_customers')->insertOrIgnore([
            [
                'id'         => 1,
                'comp'       => '077',
                'kode'       => 'CUST-001',
                'nama'       => 'PT. Fresh Food Indonesia',
                'pic'        => 'Ibu Dewi',
                'telp'       => '(021) 8899-1122',
                'email'      => 'dewi@freshfood.co.id',
                'alamat'     => 'Kawasan Industri MM2100, Blok C No.5, Bekasi',
                'termin'     => 'Net 30',
                'status'     => 'Aktif',
                'created_at' => '2026-05-12 15:07:17',
                'updated_at' => '2026-05-12 15:07:17',
            ],
            [
                'id'         => 2,
                'comp'       => '077',
                'kode'       => 'CUST-002',
                'nama'       => 'CV. Pangan Sejahtera',
                'pic'        => 'Bapak Hartono',
                'telp'       => '(021) 7788-3344',
                'email'      => 'hartono@pangansejahtera.com',
                'alamat'     => 'Jl. Raya Bogor KM 28, Cibinong',
                'termin'     => 'Net 14',
                'status'     => 'Aktif',
                'created_at' => '2026-05-12 15:07:17',
                'updated_at' => '2026-05-12 15:07:17',
            ],
            [
                'id'         => 5,
                'comp'       => '077',
                'kode'       => 'CUST-005',
                'nama'       => 'PT. Henkel Indonesia',
                'pic'        => 'Ibu Ayu',
                'telp'       => '(021) 9988-7766',
                'email'      => 'ayu@henkel.co.id',
                'alamat'     => 'Jl. Raya Bogor KM 36, Sentul',
                'termin'     => 'Net 30',
                'status'     => 'Aktif',
                'created_at' => '2026-05-12 15:07:17',
                'updated_at' => '2026-05-12 15:07:17',
            ],
        ]);

        // ── mfg_products ──────────────────────────────────────────────────────
        DB::table('mfg_products')->insertOrIgnore([
            [
                'id'         => 1,
                'comp'       => '177',
                'kode'       => 'PRD-001',
                'nama'       => 'Cup PP 200ml Bening',
                'kategori'   => 'Cup',
                'bahan'      => 'PP',
                'berat'      => 8.00,
                'harga'      => 480,
                'stok'       => 60000,
                'status'     => 'Aktif',
                'created_at' => '2026-05-12 15:07:17',
                'updated_at' => '2026-05-12 15:07:17',
            ],
            [
                'id'         => 10,
                'comp'       => '177',
                'kode'       => 'PRD-010',
                'nama'       => 'Tutup Botol PP 38mm',
                'kategori'   => 'Tutup',
                'bahan'      => 'PP',
                'berat'      => 7.00,
                'harga'      => 1200,
                'stok'       => 22000,
                'status'     => 'Aktif',
                'created_at' => '2026-05-12 15:07:17',
                'updated_at' => '2026-05-12 15:07:17',
            ],
            [
                'id'         => 14,
                'comp'       => '177',
                'kode'       => 'PRD-014',
                'nama'       => 'Galon PC 19L Biru Bening',
                'kategori'   => 'Galon',
                'bahan'      => 'PC',
                'berat'      => 850.00,
                'harga'      => 29500,
                'stok'       => 1500,
                'status'     => 'Aktif',
                'created_at' => '2026-05-12 15:07:17',
                'updated_at' => '2026-05-12 15:07:17',
            ],
        ]);

        // ── machines ──────────────────────────────────────────────────────────
        DB::table('machines')->insertOrIgnore([
            ['id' => 1, 'kode' => 'PM1-01', 'nama' => 'Extruder 1 - Cast Line',  'jenis' => 'Extruder', 'merk' => 'Windmoller',    'kapasitas' => '200 kg/jam',  'last_maint' => null, 'status' => 'Berjalan', 'proses' => 'proses-1', 'factory' => 'Pabrik Jati'],
            ['id' => 2, 'kode' => 'PM1-02', 'nama' => 'Extruder 2 - Blown Film', 'jenis' => 'Extruder', 'merk' => 'Reifenhauser', 'kapasitas' => '150 kg/jam',  'last_maint' => null, 'status' => 'Berjalan', 'proses' => 'proses-1', 'factory' => 'Pabrik Jati'],
            ['id' => 4, 'kode' => 'PM2-01', 'nama' => 'Slitting Machine 1',      'jenis' => 'Slitter',  'merk' => 'Kampf',         'kapasitas' => '500 m/menit', 'last_maint' => null, 'status' => 'Berjalan', 'proses' => 'proses-2', 'factory' => 'Pabrik Jati'],
        ]);

        // ── sales_orders ──────────────────────────────────────────────────────
        // IDs 106/108/109 tidak bentrok dengan existing seeder (IDs 1/2/3)
        DB::table('sales_orders')->insertOrIgnore([
            [
                'id'                 => 106,
                'so_number'          => 'SO/202605/0104',
                'ref_pq'             => 'PQ/202605/0023',
                'ref_bom_id'         => 62,
                'comp'               => '077',
                'customer_name'      => 'CV. Pangan Sejahtera',
                'customer_address'   => 'Jl. Raya Bogor KM 28, Cibinong',
                'customer_po_number' => 'qtr41',
                'product'            => 'Cup PP 200ml Bening',
                'qty'                => 15000000,
                'gramasi'            => 7.00,
                'satuan'             => 'Pcs',
                'harga_satuan'       => 248,
                'total'              => 3720000000,
                'delivery_date'      => '2026-06-10',
                'alamat_kirim'       => 'Jl. Raya Bogor KM 28, Cibinong',
                'notes'              => '',
                'no_po'              => 'qtr41',
                'pic'                => 'Bapak Hartono',
                'email'              => 'hartono@pangansejahtera.com',
                'telp'               => '(021) 7788-3344',
                'status'             => 'in_production',
                'created_at'         => '2026-05-20 03:06:24',
                'updated_at'         => '2026-05-20 03:06:51',
            ],
            [
                'id'                 => 108,
                'so_number'          => 'SO/202605/0106',
                'ref_pq'             => 'PQ/202605/0025',
                'ref_bom_id'         => 64,
                'comp'               => '077',
                'customer_name'      => 'PT. Fresh Food Indonesia',
                'customer_address'   => 'Kawasan Industri MM2100, Blok C No.5, Bekasi',
                'customer_po_number' => '123Ty',
                'product'            => 'Cup PP 200ml Bening',
                'qty'                => 20000,
                'gramasi'            => 7.00,
                'satuan'             => 'Pcs',
                'harga_satuan'       => 235,
                'total'              => 4700000,
                'delivery_date'      => '2026-06-25',
                'alamat_kirim'       => 'Kawasan Industri MM2100, Blok C No.5, Bekasi',
                'notes'              => '',
                'no_po'              => '123Ty',
                'pic'                => 'Ibu Dewi',
                'email'              => 'dewi@freshfood.co.id',
                'telp'               => '(021) 8899-1122',
                'status'             => 'in_production',
                'created_at'         => '2026-05-21 14:37:26',
                'updated_at'         => '2026-05-21 14:39:23',
            ],
            [
                'id'                 => 109,
                'so_number'          => 'SO/202605/0107',
                'ref_pq'             => 'PQ/202605/0026',
                'ref_bom_id'         => 65,
                'comp'               => '077',
                'customer_name'      => 'PT. Fresh Food Indonesia',
                'customer_address'   => 'Kawasan Industri MM2100, Blok C No.5, Bekasi',
                'customer_po_number' => '',
                'product'            => 'Cup PP 200ml Bening',
                'qty'                => 1000,
                'gramasi'            => 7.00,
                'satuan'             => 'Pcs',
                'harga_satuan'       => 250,
                'total'              => 250000,
                'delivery_date'      => '2026-06-25',
                'alamat_kirim'       => 'Kawasan Industri MM2100, Blok C No.5, Bekasi',
                'notes'              => '',
                'no_po'              => '',
                'pic'                => 'Ibu Dewi',
                'email'              => 'dewi@freshfood.co.id',
                'telp'               => '(021) 8899-1122',
                'status'             => 'in_production',
                'created_at'         => '2026-05-22 02:47:56',
                'updated_at'         => '2026-05-22 02:48:23',
            ],
        ]);

        // ── so_items ──────────────────────────────────────────────────────────
        // item_id 101 = Cup PP 200ml Bening (seeded di blok items atas)
        DB::table('so_items')->insertOrIgnore([
            ['id' => 1001, 'so_id' => 106, 'item_id' => 101, 'product' => 'Cup PP 200ml Bening', 'qty' => 15000000, 'gramasi' => 7.00, 'satuan' => 'Pcs', 'harga_satuan' => 248, 'created_at' => '2026-05-20 03:06:24', 'updated_at' => '2026-05-20 03:06:24'],
            ['id' => 1002, 'so_id' => 108, 'item_id' => 101, 'product' => 'Cup PP 200ml Bening', 'qty' => 20000,    'gramasi' => 7.00, 'satuan' => 'Pcs', 'harga_satuan' => 235, 'created_at' => '2026-05-21 14:37:26', 'updated_at' => '2026-05-21 14:37:26'],
            ['id' => 1003, 'so_id' => 109, 'item_id' => 101, 'product' => 'Cup PP 200ml Bening', 'qty' => 1000,     'gramasi' => 7.00, 'satuan' => 'Pcs', 'harga_satuan' => 250, 'created_at' => '2026-05-22 02:47:56', 'updated_at' => '2026-05-22 02:47:56'],
        ]);

        // ── spk ───────────────────────────────────────────────────────────────
        DB::table('spk')->insertOrIgnore([
            [
                'id'            => 47,
                'spk_number'    => 'SPK-1/202605/0015',
                'type'          => 'SPK-1',
                'comp'          => '177',
                'factory'       => 'Pabrik Jati',
                'department'    => 'PM1',
                'ref_so'        => 'SO/202605/0104',
                'ref_bom_id'    => 62,
                'product'       => 'Cup PP 200ml Bening',
                'qty'           => 15000000,
                'mesin'         => 'PM1-01',
                'tanggal'       => '2026-05-20',
                'delivery_date' => '2026-06-10',
                'notes'         => '[SPK-1 from SO/202605/0104]',
                'status'        => 'Selesai',
                'checked'       => false,
                'lot_counter'   => 0,
                'created_at'    => '2026-05-20 10:06:51',
                'updated_at'    => '2026-05-21 19:05:03',
            ],
            [
                'id'            => 49,
                'spk_number'    => 'SPK-1/202605/0016',
                'type'          => 'SPK-1',
                'comp'          => '177',
                'factory'       => 'Pabrik Jati',
                'department'    => 'PM1',
                'ref_so'        => 'SO/202605/0105',
                'ref_bom_id'    => 63,
                'product'       => 'Cup PP 200ml Bening',
                'qty'           => 1000000,
                'mesin'         => 'PM1-01',
                'tanggal'       => '2026-05-21',
                'delivery_date' => '2026-06-11',
                'notes'         => '[SPK-1 from SO/202605/0105]',
                'status'        => 'Selesai',
                'checked'       => false,
                'lot_counter'   => 0,
                'created_at'    => '2026-05-21 18:35:01',
                'updated_at'    => '2026-05-22 09:48:37',
            ],
            [
                'id'            => 53,
                'spk_number'    => 'SPK-1/202605/0018',
                'type'          => 'SPK-1',
                'comp'          => '177',
                'factory'       => 'Pabrik Jati',
                'department'    => 'PM1',
                'ref_so'        => 'SO/202605/0107',
                'ref_bom_id'    => 65,
                'product'       => 'Cup PP 200ml Bening',
                'qty'           => 1000,
                'mesin'         => 'PM1-01',
                'tanggal'       => '2026-05-22',
                'delivery_date' => '2026-06-25',
                'notes'         => '[SPK-1 from SO/202605/0107]',
                'status'        => 'Produksi',
                'checked'       => false,
                'lot_counter'   => 0,
                'created_at'    => '2026-05-22 09:48:23',
                'updated_at'    => '2026-05-22 09:48:23',
            ],
        ]);

        // ── production_orders — 1 record yang terhubung ke SPK pabrik ─────────
        // Diinsert setelah TemporaryWarehouseSeeder selesai, tidak akan ter-wipe
        DB::table('production_orders')->insertOrIgnore([
            [
                'id'              => 10,
                'sales_order_id'  => 106,
                'spk_number'      => 'SPK-1/202605/0015',
                'ref_so'          => 'SO/202605/0104',
                'production_date' => '2026-05-20',
                'item_id'         => 101,
                'planned_qty'     => 15000000,
                'status'          => 'READY',
                'factory'         => 'Pabrik Jati',
                'department'      => 'PM1',
                'mfg_product'     => 'Cup PP 200ml Bening',
                'mesin'           => 'PM1-02',
                'created_at'      => '2026-05-20 10:06:51',
                'updated_at'      => '2026-05-20 10:06:51',
            ],
        ]);

        // ── production_runs ───────────────────────────────────────────────────
        DB::table('production_runs')->insertOrIgnore([
            [
                'id'                  => 5,
                'run_number'          => 'RUN/SO/202605/0104/0001',
                'spk_id'              => 47,
                'spk_number'          => 'SPK-1/202605/0015',
                'material_request_id' => null,
                'mesin_kode'          => 'PM1-02',
                'mesin_nama'          => 'Extruder 2 - Blown Film',
                'department'          => 'PM1',
                'factory'             => 'Pabrik Jati',
                'product'             => 'Cup PP 200ml Bening',
                'qty_target'          => 161700.00,
                'operator'            => 'tedy',
                'status'              => 'completed',
                'started_at'          => '2026-05-20 11:14:22',
                'completed_at'        => '2026-05-21 19:05:03',
                'notes'               => '',
                'qty_ok'              => 661.76,
                'qty_reject'          => 0,
                'created_at'          => '2026-05-20 11:14:22',
                'updated_at'          => '2026-05-20 11:14:22',
            ],
            [
                'id'                  => 6,
                'run_number'          => 'RUN/SO/202605/0105/0001',
                'spk_id'              => 49,
                'spk_number'          => 'SPK-1/202605/0016',
                'material_request_id' => null,
                'mesin_kode'          => 'PM1-02',
                'mesin_nama'          => 'Extruder 2 - Blown Film',
                'department'          => 'PM1',
                'factory'             => 'Pabrik Jati',
                'product'             => 'Cup PP 200ml Bening',
                'qty_target'          => 30700.00,
                'operator'            => 'tedy',
                'status'              => 'completed',
                'started_at'          => '2026-05-21 19:05:31',
                'completed_at'        => '2026-05-22 09:48:37',
                'notes'               => '',
                'qty_ok'              => 491.46,
                'qty_reject'          => 0,
                'created_at'          => '2026-05-21 19:05:31',
                'updated_at'          => '2026-05-21 19:05:31',
            ],
            [
                'id'                  => 7,
                'run_number'          => 'RUN/SO/202605/0107/0001',
                'spk_id'              => 53,
                'spk_number'          => 'SPK-1/202605/0018',
                'material_request_id' => null,
                'mesin_kode'          => 'PM1-02',
                'mesin_nama'          => 'Extruder 2 - Blown Film',
                'department'          => 'PM1',
                'factory'             => 'Pabrik Jati',
                'product'             => 'Cup PP 200ml Bening',
                'qty_target'          => 11.42,
                'operator'            => 'EdyPM',
                'status'              => 'running',
                'started_at'          => '2026-05-22 09:53:16',
                'completed_at'        => null,
                'notes'               => null,
                'qty_ok'              => 0,
                'qty_reject'          => 0,
                'created_at'          => '2026-05-22 09:53:16',
                'updated_at'          => '2026-05-22 09:53:16',
            ],
        ]);

        // ── rollsheet (3 lot dari spk_id 47 = SPK-1/202605/0015) ─────────────
        DB::table('rollsheet')->insertOrIgnore([
            [
                'id'               => 23,
                'lot_number'       => 'LOT/SO/202605/0104/0001',
                'run_id'           => 5,
                'spk_id'           => 47,
                'spk_number'       => 'SPK-1/202605/0015',
                'product'          => 'Cup PP 200ml Bening',
                'mesin_kode'       => 'PM1-02',
                'operator'         => 'tedy',
                'shift'            => 'Siang',
                'berat'            => 98.31,
                'panjang'          => 0,
                'lebar'            => 0,
                'tebal'            => 0,
                'status'           => 'qc_approved',
                'lot_printed'      => true,
                'lot_printed_at'   => '2026-05-21 11:13:37',
                'qc_status'        => 'approved',
                'qr_code'          => 'QR-BATCH/SO/202605/0104/0001',
                'batch_number'     => 'BATCH/SO/202605/0104/0001',
                'pm2_status'       => 'available',
                'pm2_picked_up'    => false,
                'pm2_picked_up_at' => null,
                'pm2_picked_up_by' => null,
                'created_at'       => '2026-05-20 11:14:42',
                'updated_at'       => '2026-05-21 11:13:37',
            ],
            [
                'id'               => 25,
                'lot_number'       => 'LOT/SO/202605/0104/0003',
                'run_id'           => 5,
                'spk_id'           => 47,
                'spk_number'       => 'SPK-1/202605/0015',
                'product'          => 'Cup PP 200ml Bening',
                'mesin_kode'       => 'PM1-02',
                'operator'         => 'tedy',
                'shift'            => 'Siang',
                'berat'            => 110.12,
                'panjang'          => 0,
                'lebar'            => 0,
                'tebal'            => 0,
                'status'           => 'qc_approved',
                'lot_printed'      => true,
                'lot_printed_at'   => '2026-05-21 11:13:37',
                'qc_status'        => 'approved',
                'qr_code'          => 'QR-BATCH/SO/202605/0104/0002',
                'batch_number'     => 'BATCH/SO/202605/0104/0002',
                'pm2_status'       => 'available',
                'pm2_picked_up'    => false,
                'pm2_picked_up_at' => null,
                'pm2_picked_up_by' => null,
                'created_at'       => '2026-05-20 11:14:44',
                'updated_at'       => '2026-05-21 11:13:37',
            ],
            [
                'id'               => 26,
                'lot_number'       => 'LOT/SO/202605/0104/0004',
                'run_id'           => 5,
                'spk_id'           => 47,
                'spk_number'       => 'SPK-1/202605/0015',
                'product'          => 'Cup PP 200ml Bening',
                'mesin_kode'       => 'PM1-02',
                'operator'         => 'tedy',
                'shift'            => 'Siang',
                'berat'            => 146.87,
                'panjang'          => 0,
                'lebar'            => 0,
                'tebal'            => 0,
                'status'           => 'qc_approved',
                'lot_printed'      => true,
                'lot_printed_at'   => '2026-05-21 11:13:37',
                'qc_status'        => 'approved',
                'qr_code'          => 'QR-BATCH/SO/202605/0104/0003',
                'batch_number'     => 'BATCH/SO/202605/0104/0003',
                'pm2_status'       => 'available',
                'pm2_picked_up'    => false,
                'pm2_picked_up_at' => null,
                'pm2_picked_up_by' => null,
                'created_at'       => '2026-05-20 11:14:45',
                'updated_at'       => '2026-05-21 11:13:37',
            ],
        ]);

        // ── batch_pickup_log (3 batch dari spk_id 47) ─────────────────────────
        DB::table('batch_pickup_log')->insertOrIgnore([
            [
                'id'            => 1,
                'batch_number'  => 'BATCH/SO/202605/0104/0001',
                'lot_number'    => 'LOT/SO/202605/0104/0001',
                'spk_id'        => 47,
                'product'       => 'Cup PP 200ml Bening',
                'berat'         => 98.31,
                'qc_operator'   => 'Junet',
                'qc_printed_at' => '2026-05-20 06:51:55',
                'picked_up_by'  => null,
                'pickup_notes'  => null,
                'status'        => 'printed',
                'created_at'    => '2026-05-20 06:51:55',
                'updated_at'    => '2026-05-20 06:51:55',
            ],
            [
                'id'            => 2,
                'batch_number'  => 'BATCH/SO/202605/0104/0002',
                'lot_number'    => 'LOT/SO/202605/0104/0003',
                'spk_id'        => 47,
                'product'       => 'Cup PP 200ml Bening',
                'berat'         => 110.12,
                'qc_operator'   => 'Iqbal',
                'qc_printed_at' => '2026-05-20 16:43:54',
                'picked_up_by'  => null,
                'pickup_notes'  => null,
                'status'        => 'printed',
                'created_at'    => '2026-05-20 16:43:54',
                'updated_at'    => '2026-05-20 16:43:54',
            ],
            [
                'id'            => 3,
                'batch_number'  => 'BATCH/SO/202605/0104/0003',
                'lot_number'    => 'LOT/SO/202605/0104/0004',
                'spk_id'        => 47,
                'product'       => 'Cup PP 200ml Bening',
                'berat'         => 146.87,
                'qc_operator'   => 'Iqbal',
                'qc_printed_at' => '2026-05-20 16:50:18',
                'picked_up_by'  => null,
                'pickup_notes'  => null,
                'status'        => 'printed',
                'created_at'    => '2026-05-20 16:50:18',
                'updated_at'    => '2026-05-20 16:50:18',
            ],
        ]);
    }
}
